### ISSUE TITLE
Forge cant be installed

### ISSUE THREAD

**Issue by User-green** [Domaman202/ATLauncher-Crack#12]
Could not upload to gihub: 
1. [Images on imgur](https://imgur.com/a/H6OHpbg)
2. [Console log on pasebin](https://pastebin.com/gh8v7jAi)

**Comment by Domaman202** [comment]
Sorry, I don't know what's wrong with forge

**Comment by User-green** [comment]
In order to install forge - create instance with this luncher, than download legal ver and put it into same folder. Than install forge with ligal ver. Profit.

ПО-русски: постаить ломаную, в ломаной добавить инстанс, закрыть ломаную, скачать легальную последнюю, закинуть её в папку к ломаной, запустить легальную, поставить форж/фабрик/квилт в какой инстанс нужен, закрыть легальную, запустить ломаную. Играть. 
Если быть совсем честным, сильно я, наверно, сильно лоханулся когда открывл эту проблему, так что, наверное, стоит пояснить: то, что я описл выше, актуально для случаев, когда через пиратскую версию не выходит скачать форж - именно такая проблема у меня была выше.

**Comment by User-green** [comment]
#26
