### ISSUE TITLE
Add skin support

### ISSUE THREAD

**Issue by pmagixc** [Domaman202/ATLauncher-Crack#13]
1  year has passed, 1 new guy asking for skin support it's been over 1 year since the last one
1. is it possible
2. will you add it
3. or is it possible to add it myself
4. and is it possible to make skins downloadable from already existing real minecraft accounts

**Comment by Domaman202** [comment]
skins can be added, but only through a separate mod or minecraft client patcher, I'll deal with this a bit later... sorry for the long answer

**Comment by shubk7** [comment]
You can integrate ely.by service to add skin support, its pretty good
