### ISSUE TITLE
Won't download any instances whatsoever

### ISSUE THREAD

**Issue by Dedusmuln** [Domaman202/ATLauncher-Crack#18]
[Log](https://copy-paste.online/?code=3282)

Tried from all sources including vanilla. Same result. Might be my settings but I digress

**Comment by Domaman202** [comment]
Comrades, please understand, I am only responsible for pirated authorization, the fact that some part of atlauncher does not work for you that is not responsible for authorizing accounts is no longer my area of ​​​​work.
