### ISSUE TITLE
I can't download modpacks

### ISSUE THREAD

**Issue by NotTheDevolper** [Domaman202/ATLauncher-Crack#20]
I know that you are not responsible for problems outside the ones with the pirated authorization, but i first would like to know if this is actually not a problem with that (not sure about that) and also if i'm doing something obviously wrong or where should i ask for further help (the problem is tath it fails every time i try to download or import a modpack, but if i try just downloading a forge version it works)
[atlauncher.log](https://github.com/Domaman202/ATLauncher-Crack/files/10472621/atlauncher.log)

**Comment by Domaman202** [comment]
Interesting error though...
1. Yes, you are doing everything right.
2. Yes, I'm not a problem with pirated authorization
3. Try installing the modpack again, maybe it was a temporary problem?
4. If the modpack still does not work, contact ATL support
