### ISSUE TITLE
It is not installed.

### ISSUE THREAD

**Issue by sssHpion007** [Domaman202/ATLauncher-Crack#25]
[log.txt](https://github.com/Domaman202/ATLauncher-Crack/files/10772744/log.txt)

**Comment by Domaman202** [comment]
Know

**Comment by Domaman202** [comment]
I wait official launcher updates

**Comment by sssHpion007** [comment]
:trollface_sad:

**Comment by sssHpion007** [comment]
Теперь устанавливается, но нельзя ни профиль создать, ни версию модлоадера выбрать. Можешь примерно сказать, сколько будешь делать кряк?

**Comment by User-green** [comment]
> :trollface_sad:

Upstream. Just use previous working release. (That`s been [3.4.24.1](https://github.com/Domaman202/ATLauncher-Crack/releases/tag/v3.4.24.1) at the moment)

**Comment by User-green** [comment]
Also, I`d like for the maintainer to remove broken relese.

**Comment by Domaman202** [comment]
This work?:
https://github.com/Domaman202/ATLauncher-Crack/releases/tag/v3.4.28.4

**Comment by mmance** [comment]
[atlauncher.log](https://github.com/Domaman202/ATLauncher-Crack/files/10948911/atlauncher.log)

I too am unable to launch 3.4.28.0 or 3.4.28.4.  I am able to use 3.4.24.1.

**Comment by Domaman202** [comment]
Check new pls:
https://github.com/Domaman202/ATLauncher-Crack/releases/tag/v3.4.28.5

**Comment by haronv99** [comment]
@Domaman202 I can't create an account, I can't play, overall the launcher behaves like I'm using the "original" one... It's sad...

**Comment by Domaman202** [comment]
\:

**Comment by Domaman202** [comment]
Oh, i need fast openvpn server for tests...

**Comment by Domaman202** [comment]
Lol....

**Comment by Domaman202** [comment]
```
com.apollographql.apollo.exception.ApolloHttpException: HTTP 403
```

**Comment by Domaman202** [comment]
...

**Comment by sssHpion007** [comment]
> > :trollface_sad:
> 
> Upstream. Just use previous working release. (That`s been [3.4.24.1](https://github.com/Domaman202/ATLauncher-Crack/releases/tag/v3.4.24.1) at the moment)

It doesn't work either. I can't download the modloader...

**Comment by mmance** [comment]
3.4.28.5 loads and works for me.

**Comment by User-green** [comment]
> > > :trollface_sad:
> > 
> > 
> > Upstream. Just use previous working release. (That`s been [3.4.24.1](https://github.com/Domaman202/ATLauncher-Crack/releases/tag/v3.4.24.1) at the moment)
> 
> It doesn't work either. I can't download the modloader...

Known. Download any official ver, put it into same folder, run. Now you can install modloader with it. I am working on a normal fix, but I am nowhere near close to the finish.

**Comment by User-green** [comment]
> Check new pls: https://github.com/Domaman202/ATLauncher-Crack/releases/tag/v3.4.28.5



> ```
> com.apollographql.apollo.exception.ApolloHttpException: HTTP 403
> ```

Cloudflare. #26

**Comment by User-green** [comment]
> Oh, i need fast openvpn server for tests...

I may be able to provide one. 200 Mb/s in Ukraine would be enough?

**Comment by mmance** [comment]
I see you pulled a bunch of versions.  Is 3.4.22.1 your suggestion now?
