### ISSUE TITLE
Offer an AppImage version for Linux

### ISSUE THREAD

**Issue by Heus-Sueh** [Domaman202/ATLauncher-Crack#31]
### The Problem

it's quite annoying to keep typing commands to run the launcher it would be better to have a single executable with two clicks just to run the game

### The Solution

AppImage, even java offers a way to package in appimage with the jpackage command

### Have you checked this issue doesn't already exist?

- [X] I am sure this issue doesn't exist already

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vadim-a-yegorov** [comment]
@Heus-Sueh Actually if you use Linux as a desktop it's your personal problem

This is the way to create AppImage from jar easily:
https://github.com/danparisd/Jar2AppImage

Feel free to generate it and share with others to help other Linux users like you!

**Comment by Heus-Sueh** [comment]
> @Heus-Sueh Actually if you use Linux as a desktop it's your personal problem
> 
> This is the way to create AppImage from jar easily:
> https://github.com/danparisd/Jar2AppImage
> 
> Feel free to generate it and share with others to help other Linux users like you!
> 
> Love, Peace 

no problem, I understand it's complicated and annoying to maintain many different packages for linux 👍

**Comment by vadim-a-yegorov** [comment]
> > @Heus-Sueh Actually if you use Linux as a desktop it's your personal problem
> > This is the way to create AppImage from jar easily:
> > https://github.com/danparisd/Jar2AppImage
> > Feel free to generate it and share with others to help other Linux users like you!
> > Love, Peace
> 
> no problem, I understand it's complicated and annoying to maintain many different packages for linux 👍

Why you can't just do AppImage? I provided you pretty easy library for that

**Comment by Heus-Sueh** [comment]
> > > @Heus-Sueh Actually if you use Linux as a desktop it's your personal problem
> > > This is the way to create AppImage from jar easily:
> > > https://github.com/danparisd/Jar2AppImage
> > > Feel free to generate it and share with others to help other Linux users like you!
> > > Love, Peace
> > 
> > no problem, I understand it's complicated and annoying to maintain many different packages for linux 👍
> 
> Why you can't just do AppImage? I provided you pretty easy library for that

I'll try and I'll come back here if I succeed
