### ISSUE TITLE
Я так и не понял, в чем заключается "взлом"?

### ISSUE THREAD

**Issue by vadim-a-yegorov** [Domaman202/ATLauncher-Crack#35]
Я так и не понял, в чем заключается "взлом"?

Как мне запустить игру без купленного аккаунта Minecraft? 

<img width="1196" alt="Screen Shot 2023-06-14 at 1 06 36 PM" src="https://github.com/Domaman202/ATLauncher-Crack/assets/121871103/0b98bc9e-f7a0-4bde-86d4-44a15f1b9037">

**Comment by sssHpion007** [comment]
Взлом резиновой попы. Паходу ничё не может, можно забить.

**Comment by Domaman202** [comment]
АХХАХАХАХАХ

**Comment by Domaman202** [comment]
https://github.com/Domaman202/ATLauncher-Crack/assets/51743763/4a2d3ef0-b433-44e0-9964-058aeaaca313

**Comment by Domaman202** [comment]
> Взлом резиновой попы. Паходу ничё не может, можно забить.

Иди русский учи, юный комментатор

**Comment by Domaman202** [comment]
@vadim-a-yegorov 

Какую версию пользовал?

**Comment by Domaman202** [comment]
Качать сборки с официальной надо,
Запускать потом с моей

**Comment by vadim-a-yegorov** [comment]
> Качать сборки с официальной надо, Запускать потом с моей

Он не дает качать пока не зайдешь в аккаунт. Но я уже потерял интерес к ATLauncher, мы создали свой сервер с лончером конкурирующий с Loliland и McSkill.

**Comment by Domaman202** [comment]
> > Качать сборки с официальной надо, Запускать потом с моей
> 
> Он не дает качать пока не зайдешь в аккаунт. Но я уже потерял интерес к ATLauncher, мы создали свой сервер с лончером конкурирующий с Loliland и McSkill.

Интересно, т.к. когда я качал - у меня все работало нормально, возможно потом сделаю ещё один репозиторий, как только мне разблокируют ip на сайт ATL.

**Comment by Domaman202** [comment]
> Мы создали свой сервер с лончером конкурирующий с Loliland и McSkill.

Желаю удачи в продвижении)

**Comment by sssHpion007** [comment]
> > Взлом резиновой попы. Паходу ничё не может, можно забить.
> 
> Иди русский учи, юный комментатор

Чел ты сыночек. Причём тут вообще язык? Это у ватников такая сливная заготовочка, когда штаны забываете снимать перед тем, как обосраться?

Лучше бы говно своё допилил и позорище "русское" снял.

⠃⣿⣿⣿⣾⣿⣿⣿⣽⣿⣿⣿⣿⡿⠿⠛⠛⠻⢷⣷⣿⣿⣿⣧
⣞⣻⣿⣿⣁⣀⣀⠈⠙⠛⣿⣿⠁⠴⢛⣀⣀⣀⣀⣹⣟⡿⠿⢭
⣵⣉⣉⡙⠻⢻⣿⡿⠀⣿⣿⣿⣷⣾⣿⣿⣦⣌⣙⣉⣡⡴⠲⣶
⢽⡿⠀⣿⣿⢿⡋⠠⣾⣿⡿⠟⠧⡌⢩⣿⣿⠿⠟⢋⣡⣴⠂⣈
⢿⡇⠀⠈⡙⠻⠿⠷⠌⠹⠿⠿⠛⠒⠋⣥⣤⣶⠆⠘⢋⠁⣴⣿
⢸⡇⠈⠀⠛⠰⠶⠦⠰⠶⠆⠾⠿⠟⠃⠉⢁⣠⡄⠸⢃⣾⣿⡇
⢸⣇⠀⢀⠀⡀⢀⡀⠀⣀⣀⠀⣤⣶⣶⡘⣿⠟⢋⣴⣿⣿⣿⡇
⣿⣿⣆⡐⠂⠹⠈⠿⠄⠿⠿⠀⠻⠛⠋⣁⡤⢶⡻⢝⡫⠟⣿
⣿⣿⣿⣝⠿⣿⣷⣶⣶⣶⣶⠶⠿⣟⠯⣙⣮⠵⣿⣿⣿⣿⣿

**Comment by sssHpion007** [comment]
> > Качать сборки с официальной надо, Запускать потом с моей
> 
> Он не дает качать пока не зайдешь в аккаунт. Но я уже потерял интерес к ATLauncher, мы создали свой сервер с лончером конкурирующий с Loliland и McSkill.

А как называться будет?

**Comment by sssHpion007** [comment]
> > Взлом резиновой попы. Паходу ничё не может, можно забить.
> 
> Иди русский учи, юный комментатор

А кст, ты путлера в вк на аву специально узким сделал? Чёт прям порвало.

**Comment by Domaman202** [comment]
> > > Взлом резиновой попы. Паходу ничё не может, можно забить.
> > 
> > 
> > Иди русский учи, юный комментатор
> 
> Чел ты сыночек. Причём тут вообще язык? Это у ватников такая сливная заготовочка, когда штаны забываете снимать перед тем, как обосраться?
> 
> Лучше бы говно своё допилил и позорище "русское" снял.
> 
> ⠃⣿⣿⣿⣾⣿⣿⣿⣽⣿⣿⣿⣿⡿⠿⠛⠛⠻⢷⣷⣿⣿⣿⣧ ⣞⣻⣿⣿⣁⣀⣀⠈⠙⠛⣿⣿⠁⠴⢛⣀⣀⣀⣀⣹⣟⡿⠿⢭ ⣵⣉⣉⡙⠻⢻⣿⡿⠀⣿⣿⣿⣷⣾⣿⣿⣦⣌⣙⣉⣡⡴⠲⣶ ⢽⡿⠀⣿⣿⢿⡋⠠⣾⣿⡿⠟⠧⡌⢩⣿⣿⠿⠟⢋⣡⣴⠂⣈ ⢿⡇⠀⠈⡙⠻⠿⠷⠌⠹⠿⠿⠛⠒⠋⣥⣤⣶⠆⠘⢋⠁⣴⣿ ⢸⡇⠈⠀⠛⠰⠶⠦⠰⠶⠆⠾⠿⠟⠃⠉⢁⣠⡄⠸⢃⣾⣿⡇ ⢸⣇⠀⢀⠀⡀⢀⡀⠀⣀⣀⠀⣤⣶⣶⡘⣿⠟⢋⣴⣿⣿⣿⡇ ⣿⣿⣆⡐⠂⠹⠈⠿⠄⠿⠿⠀⠻⠛⠋⣁⡤⢶⡻⢝⡫⠟⣿ ⣿⣿⣿⣝⠿⣿⣷⣶⣶⣶⣶⠶⠿⣟⠯⣙⣮⠵⣿⣿⣿⣿⣿

Ааа, так ты у нас "патриот " 404й, я то думаю почему это от тебя говном попахивает, сразу б сказал. xD

**Comment by Domaman202** [comment]
@vadim-a-yegorov , разобрался с проблемой, прошу прочитать новый гайд в описании репозитория.
