### ISSUE TITLE
АТЛаунчеровкая команда прикрыла трюк с двумя лаунчерами

### ISSUE THREAD

**Issue by User-green** [Domaman202/ATLauncher-Crack#37]
### What happened?

Теперь оригинальный АТЛ не признаёт крякнутые акки

### Operating System

Linux

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Domaman202** [comment]
Вот черти

**Comment by Domaman202** [comment]
Ну ничего, исправим.

**Comment by Domaman202** [comment]
Прорвёмся! Как наши деды прорвались в 45м.

**Comment by Domaman202** [comment]
https://github.com/Domaman202/ATLauncher-Crack/releases/tag/v3.4.28.7

**Comment by Domaman202** [comment]
Попробуй пожалуйста :3

**Comment by User-green** [comment]
Йеп, работает как часы.
А вообще - не бомбите на АТЛовцев - они как минимум пилят отличный лаунчер.
