### ISSUE TITLE
Предложение: обрезать весь код из взломаной версии, кроме добавления аккаунтов. 

### ISSUE THREAD

**Issue by User-green** [Domaman202/ATLauncher-Crack#39]
### The Problem

То, что сейчас нужно использовать два совершенно одинаковых лаунчера - это как бы не комильфо.

### The Solution

Превратить эту версию лаунчера в такую себе "утилиту-добавить-акаунт" для оригинального АТЛ. Заодно останется только ломать новые версии АТЛ походу выхода, а не парится со ВСЕМИ фичами лаунчера.

### Have you checked this issue doesn't already exist?

- [X] I am sure this issue doesn't exist already

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Domaman202** [comment]
Norm idea

**Comment by Domaman202** [comment]
https://drive.google.com/file/d/1Yry5X-RZGSGjzdlIhMOXfjgTESTr_Fsx/view?usp=sharing

**Comment by Domaman202** [comment]
check pls
