### ISSUE TITLE
Upgrade to 3.4.30 please

### ISSUE THREAD

**Issue by drkhodakarami** [Domaman202/ATLauncher-Crack#41]
3.4.30 is now supporting neoforged loader (the continuation of forge), here is the issue from main repo :

https://github.com/ATLauncher/ATLauncher/issues/788

please upgrade to this version for supporting neoforged

thanks

**Comment by Domaman202** [comment]
https://github.com/Domaman202/ATLauncher-Crack/releases/tag/v3.4.28.9
check new

**Comment by Domaman202** [comment]
https://github.com/Domaman202/ATLauncher-Crack/releases/tag/v3.4.28.10

**Comment by drkhodakarami** [comment]
I tried it, on the surface it looks like it's creating the instance, running the game it won't show the mod button in the main menu and if you put any mod in the mod installation section of the instance, it won't load the mod, seems like it's not downloading and installing neoforge at all, only the button is there.

also, not sure what is the difference between two jar files in the release section
