### ISSUE TITLE
Building-on linux not hacked

### ISSUE THREAD

**Issue by sharpclone** [Domaman202/ATLauncher-Crack#5]
Hello my friend.
I appreciate your work but i'm having trouble with the code.
I tried building atlauncher from the source code provided ,with gradle and after many attempts i finally succedeed and got 2 versions one is Atlauncher and one is Atlauncher Shadow. They both work but they're not cracked .

I wondered if you can help me figure it out, thanks bro!

PS: If wondering why i didn't use wine , i tried it lagged and i couldn't use native linux java..

**Comment by Domaman202** [comment]
lol

**Comment by Domaman202** [comment]
Can you explain how you knew they weren't hacked?

**Comment by sharpclone** [comment]
What do mean they were hacked?

**Comment by Domaman202** [comment]
Can be played without an minecraft account
